
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from 'jspdf';

interface PdfDownloadProps {
  trip: any;
}

export default function PdfDownload({ trip }: PdfDownloadProps) {
  const { toast } = useToast();

  const generatePdf = () => {
    try {
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      let yPosition = 30;

      // Helper function to add text with word wrapping
      const addText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
        pdf.setFontSize(fontSize);
        if (isBold) pdf.setFont(undefined, 'bold');
        else pdf.setFont(undefined, 'normal');
        
        const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
        lines.forEach((line: string) => {
          if (yPosition > 270) {
            pdf.addPage();
            yPosition = 30;
          }
          pdf.text(line, margin, yPosition);
          yPosition += fontSize * 0.6;
        });
        yPosition += 5;
      };

      // Header
      addText('GetFlyNow - AI Travel Itinerary', 20, true);
      addText(`Generated on: ${new Date().toLocaleDateString()}`, 10);
      yPosition += 10;

      // Trip Details
      addText(trip.title, 16, true);
      addText(`Destination: ${trip.destination}`, 12);
      addText(`Budget: $${trip.budget}`, 12);
      addText(`Dates: ${trip.startDate} to ${trip.endDate}`, 12);
      addText(`Departure: ${trip.departureAirport}`, 12);
      yPosition += 10;

      // Budget Breakdown
      if (trip.itinerary.overview) {
        addText('BUDGET BREAKDOWN', 14, true);
        addText(`Flight Cost: $${trip.itinerary.overview.flightCost || 0}`, 12);
        addText(`Hotel Cost: $${trip.itinerary.overview.hotelCost || 0}`, 12);
        addText(`Activities Cost: $${trip.itinerary.overview.activitiesCost || 0}`, 12);
        addText(`Total Cost: $${trip.itinerary.overview.totalCost || trip.budget}`, 12, true);
        yPosition += 10;
      }

      // Daily Itinerary
      addText('DETAILED ITINERARY', 14, true);
      
      trip.itinerary.days?.forEach((day: any, index: number) => {
        addText(`DAY ${index + 1} - ${day.date}`, 13, true);
        addText(day.title, 12, true);
        addText(day.description, 11);
        yPosition += 5;
        
        day.activities?.forEach((activity: any) => {
          addText(`${activity.time} - ${activity.activity} ($${activity.cost})`, 11);
          addText(activity.description, 10);
          addText(`Category: ${activity.category}`, 10);
          yPosition += 3;
        });
        yPosition += 10;
      });

      // Footer
      yPosition += 20;
      addText('Generated by GetFlyNow - Your Free AI Travel Planner', 10);
      addText(`Visit us at: ${window.location.origin}`, 10);

      // Save the PDF
      const fileName = `${trip.destination.replace(/,/g, '-')}-itinerary.pdf`;
      pdf.save(fileName);

      toast({
        title: "PDF Downloaded",
        description: "Your trip itinerary PDF has been downloaded!",
      });
    } catch (error) {
      console.error('PDF generation error:', error);
      toast({
        title: "Download Failed",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <Button onClick={generatePdf} className="w-full sm:w-auto">
      <Download className="w-4 h-4 mr-2" />
      Download PDF Itinerary
    </Button>
  );
}
